In [28]:
import pandas as pd
parent_dir = "data_phase1"
df_cell_info = pd.read_csv(f'{parent_dir}/cell_info.txt', sep='\t')     # Metadata for cell lines (the samples of the data matrices)
df_gene_info = pd.read_csv(f'{parent_dir}/gene_info.txt', sep='\t')     # Metadata for genes (the features of the data matrices)
df_inst_info = pd.read_csv(f'{parent_dir}/inst_info.txt', sep='\t')     # Metadata for L1000 experiments (the data matrices)
df_pert_info = pd.read_csv(f'{parent_dir}/pert_info.txt', sep='\t')     # Metadata for perturbations applied in L1000 experiments
df_sig_info = pd.read_csv(f'{parent_dir}/sig_info.txt', sep='\t')       # Metadata for level 5 profiles

/tmp/ipykernel_1010253/443091508.py:5: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  df_inst_info = pd.read_csv(f'{parent_dir}/inst_info.txt', sep='\t')     # Metadata for L1000 experiments (the data matrices)
/tmp/ipykernel_1010253/443091508.py:7: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  df_sig_info = pd.read_csv(f'{parent_dir}/sig_info.txt', sep='\t')       # Metadata for level 5 profiles

In [29]:
df_sig_info

,sig_id,pert_id,pert_iname,pert_type,cell_id,pert_dose,pert_dose_unit,pert_idose,pert_time,pert_time_unit,pert_itime,distil_id
0,AML001_CD34_24H:A05,DMSO,DMSO,ctl_vehicle,CD34,0.1,%,0.1 %,24,h,24 h,AML001_CD34_24H_X1_F1B10:A05
1,AML001_CD34_24H:A06,DMSO,DMSO,ctl_vehicle,CD34,0.1,%,0.1 %,24,h,24 h,AML001_CD34_24H_X3_F1B10:A06
2,AML001_CD34_24H:B05,DMSO,DMSO,ctl_vehicle,CD34,0.1,%,0.1 %,24,h,24 h,AML001_CD34_24H_X1_F1B10:B05|AML001_CD34_24H_X...
3,AML001_CD34_24H:B06,DMSO,DMSO,ctl_vehicle,CD34,0.1,%,0.1 %,24,h,24 h,AML001_CD34_24H_X3_F1B10:B06
4,AML001_CD34_24H:BRD-A03772856:0.37037,BRD-A03772856,BRD-A03772856,trt_cp,CD34,0.37037,µM,500 nM,24,h,24 h,AML001_CD34_24H_X1_F1B10:J04|AML001_CD34_24H_X...
...,...,...,...,...,...,...,...,...,...,...,...,...
473642,TAK004_U2OS_96H:TRCN0000370007:1,TRCN0000370007,WWTR1,trt_sh,U2OS,1.0,µL,1 µL,96,h,96 h,TAK004_U2OS_96H_X1_B6_DUO52HI53LO:J10|TAK004_U...
473643,TAK004_U2OS_96H:TRCN0000370678:1,TRCN0000370678,GRB10,trt_sh,U2OS,1.0,µL,1 µL,96,h,96 h,TAK004_U2OS_96H_X1_B6_DUO52HI53LO:E02|TAK004_U...
473644,TAK004_U2OS_96H:TRCN0000370697:1,TRCN0000370697,GRB10,trt_sh,U2OS,1.0,µL,1 µL,96,h,96 h,TAK004_U2OS_96H_X1_B6_DUO52HI53LO:A18|TAK004_U...
473645,TAK004_U2OS_96H:TRCN0000370751:1,TRCN0000370751,GRB10,trt_sh,U2OS,1.0,µL,1 µL,96,h,96 h,TAK004_U2OS_96H_X1_B6_DUO52HI53LO:I12|TAK004_U...
473646,TAK004_U2OS_96H:TRCN0000381509:1,TRCN0000381509,CDC42,trt_sh,U2OS,1.0,µL,1 µL,96,h,96 h,TAK004_U2OS_96H_X1_B6_DUO52HI53LO:L01|TAK004_U...

In [30]:
# join df_sig_info with df gene_info to get gene info on the perturbed genes
df_perturbed_genes = df_sig_info.merge(df_gene_info, left_on='pert_iname', right_on='pr_gene_symbol', how='inner')#
df_perturbed_genes

,sig_id,pert_id,pert_iname,pert_type,cell_id,pert_dose,pert_dose_unit,pert_idose,pert_time,pert_time_unit,pert_itime,distil_id,pr_gene_id,pr_gene_symbol,pr_gene_title,pr_is_lm,pr_is_bing
0,CGS001_A375_96H:A2M:1,CGS001-2,A2M,trt_sh.cgs,A375,1.0,µL,1 µL,96,h,96 h,KDC004_A375_96H:TRCN0000006653:-666|KDC004_A37...,2,A2M,alpha-2-macroglobulin,0,1
1,CGS001_A375_96H:AARS:1,CGS001-16,AARS,trt_sh.cgs,A375,1.0,µL,1 µL,96,h,96 h,KDB006_A375_96H:TRCN0000045688:-666|KDB006_A37...,16,AARS,alanyl-tRNA synthetase,1,1
2,CGS001_A375_96H:AATF:1,CGS001-26574,AATF,trt_sh.cgs,A375,1.0,µL,1 µL,96,h,96 h,KDA004_A375_96H:TRCN0000017389:-666|KDA004_A37...,26574,AATF,apoptosis antagonizing transcription factor,0,1
3,CGS001_A375_96H:ABAT:1,CGS001-18,ABAT,trt_sh.cgs,A375,1.0,µL,1 µL,96,h,96 h,KDA002_A375_96H:TRCN0000034925:-666|KDB006_A37...,18,ABAT,4-aminobutyrate aminotransferase,0,1
4,CGS001_A375_96H:ABCA1:1,CGS001-19,ABCA1,trt_sh.cgs,A375,1.0,µL,1 µL,96,h,96 h,KDC004_A375_96H:TRCN0000029089:-666|KDC004_A37...,19,ABCA1,ATP binding cassette subfamily A member 1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
193497,TAK004_U2OS_96H:TRCN0000370007:1,TRCN0000370007,WWTR1,trt_sh,U2OS,1.0,µL,1 µL,96,h,96 h,TAK004_U2OS_96H_X1_B6_DUO52HI53LO:J10|TAK004_U...,25937,WWTR1,WW domain containing transcription regulator 1,0,1
193498,TAK004_U2OS_96H:TRCN0000370678:1,TRCN0000370678,GRB10,trt_sh,U2OS,1.0,µL,1 µL,96,h,96 h,TAK004_U2OS_96H_X1_B6_DUO52HI53LO:E02|TAK004_U...,2887,GRB10,growth factor receptor bound protein 10,1,1
193499,TAK004_U2OS_96H:TRCN0000370697:1,TRCN0000370697,GRB10,trt_sh,U2OS,1.0,µL,1 µL,96,h,96 h,TAK004_U2OS_96H_X1_B6_DUO52HI53LO:A18|TAK004_U...,2887,GRB10,growth factor receptor bound protein 10,1,1
193500,TAK004_U2OS_96H:TRCN0000370751:1,TRCN0000370751,GRB10,trt_sh,U2OS,1.0,µL,1 µL,96,h,96 h,TAK004_U2OS_96H_X1_B6_DUO52HI53LO:I12|TAK004_U...,2887,GRB10,growth factor receptor bound protein 10,1,1
193501,TAK004_U2OS_96H:TRCN0000381509:1,TRCN0000381509,CDC42,trt_sh,U2OS,1.0,µL,1 µL,96,h,96 h,TAK004_U2OS_96H_X1_B6_DUO52HI53LO:L01|TAK004_U...,998,CDC42,cell division cycle 42,1,1

In [31]:
#get unique perturbed genes
unique_perturbed_genes = df_perturbed_genes['pert_iname'].unique()
unique_perturbed_genes

array(['A2M', 'AARS', 'AATF', ..., 'OLFML3', 'GPR183', 'SLC9A5'],
      shape=(4235,), dtype=object)

In [32]:
# print columns of all dataframes
print("Cell info columns:", df_cell_info.columns.tolist())
print("Gene info columns:", df_gene_info.columns.tolist())
print("Instance info columns:", df_inst_info.columns.tolist())
print("Perturbation info columns:", df_pert_info.columns.tolist())
print("Signature info columns:", df_sig_info.columns.tolist())

Cell info columns: ['cell_id', 'cell_type', 'base_cell_id', 'precursor_cell_id', 'modification', 'sample_type', 'primary_site', 'subtype', 'original_growth_pattern', 'provider_catalog_id', 'original_source_vendor', 'donor_age', 'donor_sex', 'donor_ethnicity']
Gene info columns: ['pr_gene_id', 'pr_gene_symbol', 'pr_gene_title', 'pr_is_lm', 'pr_is_bing']
Instance info columns: ['inst_id', 'rna_plate', 'rna_well', 'pert_id', 'pert_iname', 'pert_type', 'pert_dose', 'pert_dose_unit', 'pert_time', 'pert_time_unit', 'cell_id']
Perturbation info columns: ['pert_id', 'pert_iname', 'pert_type', 'is_touchstone', 'inchi_key_prefix', 'inchi_key', 'canonical_smiles', 'pubchem_cid']
Signature info columns: ['sig_id', 'pert_id', 'pert_iname', 'pert_type', 'cell_id', 'pert_dose', 'pert_dose_unit', 'pert_idose', 'pert_time', 'pert_time_unit', 'pert_itime', 'distil_id']

In [33]:
# # for df_perturbed_genes plot the value counts for all Perturbed Genes')
# import matplotlib.pyplot as plt
# df_perturbed_genes['pert_iname'].value_counts().plot(kind='bar')
# plt.xlabel('Perturbed Genes')
# plt.ylabel('Frequency')
# plt.title('Distribution of Perturbed Genes')
# plt.show()

In [34]:
import json
import os

parent_dir = "../kegg_data"

# read kegg_nodes.json
kegg_nodes_path = os.path.join(parent_dir, "kegg_nodes.json")
with open(kegg_nodes_path, "r", encoding="utf-8") as fin:
    kegg_nodes = json.load(fin)

metrics = {}
unique_perturbed_set = set(unique_perturbed_genes)
for pathway, dict in kegg_nodes.items():
    nodes = dict.get('nodes', [])
    num_edges = dict.get('edges', 0)
    if not isinstance(nodes, (list, tuple, set)):
        raise ValueError(f"nodes for pathway {pathway!r} must be a list-like object")
    nodes_list = list(nodes)
    num_nodes = len(nodes_list)

    # directed adjacency without self-loops as in prior code (each ordered pair counted)
    avg_degree = num_edges / num_nodes
    density = num_edges / (num_nodes * num_nodes)

    num_perturbed_in_pathway = sum(1 for node in nodes_list if node in unique_perturbed_set)
    node_set = set(nodes_list)
    num_sig_info_in_pathway = int(df_sig_info['pert_iname'].isin(node_set).sum())

    metrics[pathway] = {
        'number_of_nodes': int(num_nodes),
        'number_of_edges': int(num_edges),
        'average_degree': float(avg_degree),
        'density': float(density),
        'number_of_perturbed_genes_in_pathway': int(num_perturbed_in_pathway),
        'number_of_sig_info_in_pathway': int(num_sig_info_in_pathway)
    }

out_path = os.path.join(parent_dir, "kegg_nodes_metrics.json")
with open(out_path, "w", encoding="utf-8") as fout:
    json.dump(metrics, fout, indent=4, ensure_ascii=False)

print(f"Wrote metrics for {len(metrics)} pathways to {out_path}")

Wrote metrics for 17 pathways to ../kegg_data/kegg_nodes_metrics.json

# we choose cellline a549

In [35]:
df_inst_info =df_inst_info[df_inst_info['cell_id'] == 'A549']
#count values pert_type
df_inst_info['pert_type'].value_counts()

pert_type
trt_cp         57775
trt_sh         39686
trt_oe          6702
ctl_vehicle     2847
ctl_vector      2117
trt_lig         1738
ctl_untrt       1554
Name: count, dtype: int64

In [36]:
df_sig_info

,sig_id,pert_id,pert_iname,pert_type,cell_id,pert_dose,pert_dose_unit,pert_idose,pert_time,pert_time_unit,pert_itime,distil_id
0,AML001_CD34_24H:A05,DMSO,DMSO,ctl_vehicle,CD34,0.1,%,0.1 %,24,h,24 h,AML001_CD34_24H_X1_F1B10:A05
1,AML001_CD34_24H:A06,DMSO,DMSO,ctl_vehicle,CD34,0.1,%,0.1 %,24,h,24 h,AML001_CD34_24H_X3_F1B10:A06
2,AML001_CD34_24H:B05,DMSO,DMSO,ctl_vehicle,CD34,0.1,%,0.1 %,24,h,24 h,AML001_CD34_24H_X1_F1B10:B05|AML001_CD34_24H_X...
3,AML001_CD34_24H:B06,DMSO,DMSO,ctl_vehicle,CD34,0.1,%,0.1 %,24,h,24 h,AML001_CD34_24H_X3_F1B10:B06
4,AML001_CD34_24H:BRD-A03772856:0.37037,BRD-A03772856,BRD-A03772856,trt_cp,CD34,0.37037,µM,500 nM,24,h,24 h,AML001_CD34_24H_X1_F1B10:J04|AML001_CD34_24H_X...
...,...,...,...,...,...,...,...,...,...,...,...,...
473642,TAK004_U2OS_96H:TRCN0000370007:1,TRCN0000370007,WWTR1,trt_sh,U2OS,1.0,µL,1 µL,96,h,96 h,TAK004_U2OS_96H_X1_B6_DUO52HI53LO:J10|TAK004_U...
473643,TAK004_U2OS_96H:TRCN0000370678:1,TRCN0000370678,GRB10,trt_sh,U2OS,1.0,µL,1 µL,96,h,96 h,TAK004_U2OS_96H_X1_B6_DUO52HI53LO:E02|TAK004_U...
473644,TAK004_U2OS_96H:TRCN0000370697:1,TRCN0000370697,GRB10,trt_sh,U2OS,1.0,µL,1 µL,96,h,96 h,TAK004_U2OS_96H_X1_B6_DUO52HI53LO:A18|TAK004_U...
473645,TAK004_U2OS_96H:TRCN0000370751:1,TRCN0000370751,GRB10,trt_sh,U2OS,1.0,µL,1 µL,96,h,96 h,TAK004_U2OS_96H_X1_B6_DUO52HI53LO:I12|TAK004_U...
473646,TAK004_U2OS_96H:TRCN0000381509:1,TRCN0000381509,CDC42,trt_sh,U2OS,1.0,µL,1 µL,96,h,96 h,TAK004_U2OS_96H_X1_B6_DUO52HI53LO:L01|TAK004_U...